name: Deploy Hugo site to GitHub Pages


on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to 'main' branch (or your default branch)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'  # Specify the version of Hugo you want to use

    - name: Build the Hugo site
      run: hugo --minify  # Build the site and minify the output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # The output directory for Hugo
        publish_branch: gh-pages  # The branch to deploy to (e.g., 'gh-pages')
